---
# https://linuxconfig.org/how-to-install-docker-in-rhel-8
# You should be using podman and buildah instead!

- name: Uninstall old versions
  apt:
    name: >-
        docker, docker-engine, docker.io,
        containerd, runc
    state: absent

- name: add Docker apt signing key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg

- name: setup Docker apt repository on Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    update_cache: yes
    name: "{{ ubuntu_prereq_packages }}"
    state: present

- name: Install Docker-CE
  apt:
    update_cache: yes
    name: "{{ ubuntu_docker_packages }}"
    state: present
