---
# tasks file for vmtools

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_major_version == '8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_major_version >= "7" )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version == "30" )
        ) or
        ( ansible_distribution == "Debian" and ( ansible_distribution_major_version == "9" or ansible_distribution_major_version == "10" )
        ) or
        ( ansible_distribution == "Ubuntu" and ( ansible_distribution_version == "18.04" )
        )
      - ansible_virtualization_role == "guest"

# VirtualBox
- include: VirtualBox.yml
  when: ansible_virtualization_type == "virtualbox"

# VMware
- include: VMware.yml
  when: ansible_virtualization_type == "vmware"

# KVM
- include: KVM.yml
  when: ansible_virtualization_type == "kvm"
