---
# defaults file for virtualbox

# Add users to 'vboxusers' group
setup_users: yes

# List of users to add to 'vboxusers' group
vbox_users:
  - cmihai

# VirtualBox major version to install
virtualbox_version: "6.0"

# Full version number
virtualbox_version_full: "6.0.12"

# Install extensions listed in virtualbox_extpacks_urls
install_extpacks: yes

# List of VirtualBox extensions to install
virtualbox_extpack_urls:
  - "https://download.virtualbox.org/virtualbox/{{ virtualbox_version_full }}/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version_full }}.vbox-extpack"
