---
# vars file for vmware

vmware_required_packages_centos_7:
  - libXinerama
  - pcsc-lite-libs
  - kernel-devel
  - kernel-headers
  - "@Development Tools"
  - ncurses-libs

vmware_required_packages_rhel_8:
  - libXinerama
  - libXtst
  - pcsc-lite-libs
  - kernel-devel
  - kernel-headers
  - ncurses-compat-libs

vmware_required_packages_fedora_30:
  - libXinerama
  - pcsc-lite-libs
  - kernel-devel
  - kernel-headers
  - elfutils-libelf-devel
  - "@Development Tools"
  - ncurses-compat-libs

vmware_required_packages_ubuntu_1804:
  - build-essential
  - libncursesw5
  - gcc
  - libpcsclite1
  - "linux-headers-{{ ansible_kernel }}"

vmware_required_packages_debian_10:
  - build-essential
  - libncursesw5
  - gcc
  - libpcsclite1
  - "linux-headers-{{ ansible_kernel }}"
