---
# tasks file for podman

- include: install_CentOS.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version']|int <= 7

- include: install_RedHat.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int <= 8

- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int == 30

- include: install_Ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "18.04"

- include: configure.yml
  when: ansible_facts['distribution'] != 'Debian'
