---
galaxy_info:
  author: Mihai Criveti
  description: Docker_ce
  company: Mihai Criveti
  license: MIT
  min_ansible_version: 2.4

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Fedora
      versions:
        - all
        - 30
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - buster

  galaxy_tags:
    - debian
    - ubuntu
    - rhel
    - centos
    - fedora

# dependencies: []
