---
# defaults file for vmware_workstation

# Download VMware Workstation Pro 15.1
vmware_bundle_url: "https://www.vmware.com/go/getworkstation-linux"
vmware_bundle_checksum: "sha256:55f8b9d4015fa958eba1aac72cc9985d34f22d1df5d027d7c34f1f4bf4f0c01d"
cleanup_vmware_bundle: false

# Patch VMware Host Modules for Fedora 30 / Kernel 5.1
fedora_30_vmware_patch_release: "w15.1.0-k5.1"
fedora_30_vmware_patch_url: "https://github.com/mkubecek/vmware-host-modules/archive/{{ fedora_30_vmware_patch_release }}.tar.gz"
fedora_30_vmware_patch_checksum: "sha256:5afcace6fc0b287d036d302af078ce22f1f7a33f8a4f6654f5f63b6b95e36dc5"

