---
# Install prereqs on CentOS 7

- name: install requirements on CentOS 7
  yum:
    name: "{{ vmware_required_packages_centos_7 }}"
    state: present
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version']|int == 7
