---
# tasks file for vmware_workstation

- include: install_CentOS.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version']|int <= 7

- include: install_RedHat.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int <= 8

- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int == 30

- include: install_Ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "18.04"

- include: install_Debian.yml
  when: ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_version']|int >= 10

- include: install_VMware.yml

- include: patch_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version']|int == 30

- include: configure.yml
